# Generated by Django 4.2.10 on 2024-07-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JaMoveo', '0002_alter_customuser_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_admin',
            field=models.BooleanField(default=True),
        ),
    ]
